workspace:
  base: /go
  path: src/gitlab.com/coresec.xyz/GoCSshell

pipeline:
  test:
    image: golang:latest
    commands:
      - go vet
      - go test -v -cover
  build:
    image: golang:latest
    commands:
      - go build
